name: MyPy

on: push

jobs:
  type-check:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python & PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: true

      - name: Install dependencies
        run: pdm sync -d

      - name: Run linting
        run: pdm run mypy